host = "127.0.0.1"
logpath = "./log/log"

[webconf]
port = "3002"

[thriftconf]
port = "3000"

[redisconf]
maxidle = 3
idle_timeout = 300
host = "127.0.0.1"
port = "6379"

[mysqlconf]
host = "127.0.0.1"
port = "3306"
database = "test"
user = "root"
password = ""
protocol = "tcp"